# Generated by Django 2.0.7 on 2018-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[(0, 'Niezdefiniowany'), (1, 'Domowy'), (2, 'Służbowy'), (3, 'Prywatny')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[(0, 'Niezdefiniowany'), (1, 'Domowy'), (2, 'Służbowy'), (3, 'Prywatny')], default=0, max_length=1),
        ),
    ]
